#+title: Notes

* Getting Started
https://vulkan.lunarg.com/doc/sdk/1.4.313.0/linux/getting_started.html

- need to do something with installed driver manifest?
  If you have installed a Vulkan driver from a GPU vendor, you may wish to verify there is a .json manifest file for that driver installed. This will normally be located in either /etc/vulkan/icd.d/ or /usr/share/vulkan/icd.d (though other locations are possible). These directories will contain one or more Vulkan driver .json manifest files, which are not modified by the SDK installer. Refer to the Vulkan Loader guide in the "ICD Discovery on Linux" section for detailed information on ICD and layer library search order and paths for this platform.
  https://vulkan.lunarg.com/doc/view/1.4.313.0/linux/loader_and_layer_interface.html#user-content-linux-layer-discovery

  on pop os, these can be set by environment variable
  https://github.com/pop-os/system76-power/issues/153


* Other Graphics Resources
- ray tracing in one weekend
  https://github.com/RayTracing/raytracing.github.io
- PBR Book
  https://www.pbr-book.org/
- Learning Modern 3D Graphics Programming
  https://paroj.github.io/gltut/

* Depencencies
- Vulkan SDK
- SDL
** Slang
https://shader-slang.org/tools/
- part of Vulkan SDK, can also be downloaded independently
- there's a VSCode extension, and maybe an LSP?
  it's some kind of custom daemon, not an LSP
